In [218]:
import numpy as np

a_rest = np.array([7569,-1699,-365,1])
a_upside_down = np.array([-8361,1051,1700,1])
a_nose_up = np.array([1062,-293,8702,1])
a_nose_down = np.array([-1534,-366,-7455,1])
a_left = np.array([1241,7866,1147,1])
a_right = np.array([-1365,-8199,531,1])

aa_rest = np.array([0,0,-1])
aa_upside_down = np.array([0,0,1])
aa_nose_up = np.array([1,0,0])
aa_nose_down = np.array([-1,0,0])
aa_left = np.array([0,-1,0])
aa_right = np.array([0,1,0])

In [219]:
np.linalg.norm(a_rest)

7765.9248000479638

In [220]:
np.linalg.norm(a_raw_upside_down)

8603.2890222286496

In [221]:
a_nose_up + a_nose_down

array([-472, -659, 1247,    2])

In [222]:
a_rest + a_upside_down

array([-792, -648, 1335,    2])

In [223]:
(a_rest+a_upside_down+a_nose_up+a_nose_down)/4

array([-316, -327,  645,    1])

In [224]:
y = np.array([aa_rest,aa_upside_down,aa_nose_up,aa_nose_down,aa_left,aa_right])
#y *= 1000

In [225]:
a = np.array([a_rest,a_upside_down,a_nose_up,a_nose_down,a_left,a_right])
a

array([[ 7569, -1699,  -365,     1],
       [-8361,  1051,  1700,     1],
       [ 1062,  -293,  8702,     1],
       [-1534,  -366, -7455,     1],
       [ 1241,  7866,  1147,     1],
       [-1365, -8199,   531,     1]])

In [226]:
ai = np.linalg.pinv(a)

In [227]:
np.dot(ai,a)

array([[ 1.,  0.,  0., -0.],
       [-0.,  1.,  0., -0.],
       [ 0., -0.,  1.,  0.],
       [-0.,  0., -0.,  1.]])

In [228]:
np.set_printoptions(precision=4,suppress=True)
x = np.dot(ai,y)
x

array([[ 0.    , -0.    , -0.0001],
       [-0.    , -0.0001,  0.    ],
       [ 0.0001,  0.    ,  0.    ],
       [-0.0848, -0.0406, -0.0362]])

In [229]:
np.set_printoptions(precision=10,suppress=True)
np.dot(a,x)

array([[-0.0075691156,  0.0097427118, -0.9814691973],
       [-0.0068051627,  0.0089319589,  1.0173763654],
       [ 0.9893674542,  0.0069830886, -0.0017728495],
       [-1.0097181986,  0.006161653 , -0.0025368025],
       [ 0.0169517935, -1.015525725 , -0.0153933816],
       [ 0.0177732291,  0.9837063128, -0.0162041345]])

In [230]:
np.dot([7619,-1471,-335,1],x)

array([-0.0048109753, -0.018814026 , -0.9826080169])

In [231]:
np.dot([7636,-1315,-373,1],x)
np.dot([7545,-1638,-648,1],x)

array([-0.0427129719,  0.0017369818, -0.9828866367])

In [232]:
x

array([[ 0.0000144756, -0.0000203849, -0.0001197524],
       [-0.0000070556, -0.0001212882,  0.0000187399],
       [ 0.0001214348,  0.0000038742,  0.0000192036],
       [-0.0847985645, -0.0406184776, -0.0362150665]])